sudo: required
services: docker
addons:
  apt:
    packages:
      - moreutils

script:
  - bash -eo pipefail -c "make container push | ts '[%H:%M:%S]'"

env:
  global:
  - secure: PQOn3w4lSk9+QF36oi8X1u4N2G6iNeC4Eu+NBq4Et6T/Q2lJkmjeM9fJO3kP7s2xIx16Nu5/uIZw+dIDZsc+CyTNHepAfZHGIs29ydrvVhaQSp4D1J0c/FERUMzurSjXA52TlJ1R55oMn25byu0MjkAHvRljFGDn7ARTpEAxYKE97SgG8nYwbaV2qtQInyZt9lNV4GYdqu9IbQoHjux7ekfo2Gw86vu58OMZEPACMO8Va1DqvXlfZKvPnCs5N6ZQ2cSS0Z7mmvZKlwkTDt93iFnJvngpsnxSEfAeQfCVG+BhIMP2ndfnuspPWWDjKaZVS1uN0cTfb7LRPOXnzyoQi76CiBA5XLK3pEgjcSFcxwTby+CljVvc/mszE0R51XaE7qDE0Yvm+u72Wogi40/m8Waz5y/LB5RHIxEUmarBZbqZsDRVrmr3YA8wBPWPsapAvFwnPFVdi7TfCMH604eMbEHVmVwKqLq/7t6r4Ii9MPKrC15hl5avDMT6w411QN1qay4jqdFAvok2r8zK/ZQvn4aLfbBjSnSjS3WqL8iqL2xSK5Blo2DzgTBxgJudlvg6OCZ4gcT9bCUkj+3LpNsT5HZ857TfsTZ98kqIyt2/nqPUHSWbUAu121UsOwi+oLjoVgyObfkJGUEfNXb76fbXhRqJXrgJ4ahRiIWR+GFnFA4=
