#!/bin/sh
PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

# md raid
copy_exec /sbin/mdadm /sbin
# lvm
copy_exec /sbin/dmsetup
copy_exec /sbin/lvm
ln -s lvm ${DESTDIR}/sbin/vgchange
for x in dm_mod dm_snapshot dm_mirror dm_raid; do
    manual_add_modules ${x}
done

# partitioning
for x in fdisk cfdisk parted e2fsck mke2fs mkntfs e2fsck fsck.fat; do
    copy_exec /sbin/${x}
done

exit 0
