FROM ubuntu:18.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
        openssh-client busybox xz-utils wget

COPY toolshed.img.xz /

CMD ["/bin/bash"]
