#!/bin/bash
set -eu

WORKDIR=$PWD

exec qemu-system-x86_64 \
    -m 512 \
    -nographic \
    -display curses \
    -append "root=/dev/sda1 rw console=ttyS0 net.ifnames=0 biosdevname=0" \
    -device e1000,netdev=net0 \
    -netdev user,id=net0,hostfwd=tcp::5555-:22 \
    -kernel "${WORKDIR}/.tmp/vmlinuz" \
    -initrd "${WORKDIR}/.tmp/initrd.img" \
    -hda "${WORKDIR}/toolshed.img"
